# This is a basic workflow to build and deploy your open textbook with Bookdown.

name: Bookdown

# Controls when the action will run. Triggers the workflow on push
# events but only for the main branch
on:
  push:
    branches: 
      - main

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container: 
      image: r-base:latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1
    - name: Install pandoc and citeproc
      run: |
        brew install pandoc
        brew install pandoc-citeproc
    - name: Install System Dependencies
      run: sudo apt-get update && apt-get install -y --no-install-recommends
    - name: Install Bookdown
      run: |-
         Rscript -e "install.packages('bookdown', repos = 'https://demo.rstudiopm.com/all/__linux__/bionic/latest')"
    - name: Build book
      run: |-
        Rscript -e "bookdown::render_book('index.Rmd', 'bookdown::gitbook')"
    - name: Deploy to GitHub Pages
      uses: Cecilapp/GitHub-Pages-deploy@master
      env:
        EMAIL: chris-diaz@northwestern.edu # must be a verified email
        GH_TOKEN: ${{ secrets.GH_PAT }} # https://github.com/settings/tokens
        BUILD_DIR: _book/                     # "_site/" by default
