# This is a basic workflow to build and deploy your open textbook with Bookdown.

on:
  push:
    branches: 
      - main

name: Bookdown

# Controls when the action will run. Triggers the workflow on push
# events but only for the main branch

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macos-latest
    steps:

    - name: Checkout Repository
      uses: actions/checkout@v2
      
    - name: Install pandoc and citeproc
      run: |
        brew install pandoc
        brew install pandoc-citeproc

    - name: Build book
      run: Rscript -e 'bookdown::render_book("index.Rmd", quiet = TRUE)'
      
    - name: Deploy to GitHub Pages
      uses: Cecilapp/GitHub-Pages-deploy@master
      env:
        EMAIL: chris-diaz@northwestern.edu # must be a verified email
        GH_TOKEN: ${{ secrets.GH_PAT }} # https://github.com/settings/tokens
        BUILD_DIR: _book/                     # "_site/" by default
